services:
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    ports:
      - ${FRONT_END_PORT}:${FRONT_END_PORT}
    working_dir: /app
    command: npm run setup
    depends_on:
      - api-users

  api-users:
    image: node:20-alpine
    volumes:
      - ./backend/api-users:/app
    ports:
      - ${API_USERS_PORT}:${API_USERS_PORT}
    working_dir: /app
    command: npm run setup
    depends_on:
      - database

  weight-service:
    image: node:20-alpine
    volumes:
      - ./backend/weight-service:/app
    ports:
      - 3001:3001
    working_dir: /app
    command: npm run setup
    depends_on:
      - database-weight

  database:
    image: postgres:16-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  database-weight:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=weight

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
      - ADMINER_DEFAULT_DB_DRIVER=${ADMINER_DEFAULT_DB_DRIVER} 
    depends_on:
      - database
      - database-weight
    restart: always

 
volumes:
  postgres_data: