services:
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    working_dir: /app
    command: npm run setup
    depends_on:
      - api-users

  api-users:
    image: node:20-alpine
    volumes:
      - ./backend/api-users:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: npm run setup
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database

volumes:
  postgres_data: