services:
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    working_dir: /app
    command: npm run setup
    depends_on:
      - api-users

  api-users:
    image: node:20-alpine
    volumes:
      - ./backend/api-users:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: npm run setup
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
      - ADMINER_DEFAULT_DB_DRIVER=${ADMINER_DEFAULT_DB_DRIVER} 
    depends_on:
      - database
    restart: always

volumes:
  postgres_data: